apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: web
    kind: frontend
spec:
  template:
    metadata:
      name: busybox
      labels:
        app: web
        type: frontend
    spec:
      containers:
        - command:
          - sleep
          - "3600"
      image: busybox
      name: busybox-container
  replicas: 3
  selector:
    matchLabels:
      type: frontend